name: Continues Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: NPM Install/Build/Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install, lint, test, and build
        run: npm run build:github
